# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161117_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='squaduser',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
