# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_squaduser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
