# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='name',
        ),
    ]
